development:
  :admin_list: admin
  :local_mode: true
  :ezid_host: ezid.lib.purdue.edu
  :ezid_username: apitest
  :ezid_password: apitest
  :ezid_shoulder: doi:10.5072/FK2
  :ezid_placeholder_identifier: 10.5072/FK2
  :datafile_store_dir:  /uploads
  :delayed_job_pid_dir: /tmp/pids
  :orcid_token: ORCID_TOKEN
  :key_prefix: idbdev
  :agreements_root_path: /agreements
  :root_url_text: "http://localhost:3000"
  :system_user_name: "System"
  :system_user_email: "system@example.edu"
  #You can set anything here that you might pass to Bunny.new. Anything you don't set just gets the Bunny default.
  #Typical fields needed for our setup are shown below.
  amqp:
    #ssl: true
    #port: 5761 #this is the default port for ssl connections
    #host: 127.0.0.1
    #user: user
    #password: pw
    #vhost: medusa
    #verify_peer: false
  medusa:
    #AMQP queues to communicate with glacier server
    outgoing_queue: idb_to_medusa
    incoming_queue: medusa_to_idb

test:
  :admin_list: admin
  :local_mode: true
  :ezid_host: ezid.lib.purdue.edu
  :ezid_username: apitest
  :ezid_password: apitest
  :ezid_shoulder: doi:10.5072/FK2
  :ezid_placeholder_identifier: 10.5072/FK2
  :datafile_store_dir:  /uploads
  :delayed_job_pid_dir: /tmp/pids
  :orcid_token: ORCID_TOKEN
  :key_prefix: idbtest
  #You can set anything here that you might pass to Bunny.new. Anything you don't set just gets the Bunny default.
  #Typical fields needed for our setup are shown below.
  amqp:
    #ssl: true
    #port: 5761 #this is the default port for ssl connections
    #host: 127.0.0.1
    #user: user
    #password: pw
    #vhost: medusa
    #verify_peer: false
  medusa:
    #AMQP queues to communicate with glacier server
    outgoing_queue: idb_to_medusa
    incoming_queue: medusa_to_idb

production:
  :admin_list: <%= ENV["ADMIN_LIST"] %>
  :local_mode: false
  :ezid_host: ezid.lib.purdue.edu
  :ezid_username: <%= ENV["EZID_USERNAME"] %>
  :ezid_password: <%= ENV["EZID_PASSWORD"] %>
  :ezid_shoulder: <%= ENV["EZID_SHOULDER"] %>
  :ezid_placeholder_identifier: 10.5072/FK2
  :datafile_store_dir:  <%= ENV["DATAFILE_STORE_DIR"] %>
  :delayed_job_pid_dir: <%= ENV["PIDS_DIR"] %>
  :orcid_token: ORCID_TOKEN
  :key_prefix: idb
  #You can set anything here that you might pass to Bunny.new. Anything you don't set just gets the Bunny default.
  #Typical fields needed for our setup are shown below.
  amqp:
    #ssl: true
    #port: 5761 #this is the default port for ssl connections
    #host: 127.0.0.1
    #user: user
    #password: pw
    #vhost: medusa
    #verify_peer: false
  medusa:
    #AMQP queues to communicate with glacier server
    outgoing_queue: idb_to_medusa
    incoming_queue: medusa_to_idb