development:
  :admin_list: admin
  :local_mode: true
  :ezid_host: ezid.lib.purdue.edu
  :ezid_username: apitest
  :ezid_password: apitest
  :ezid_shoulder: doi:10.5072/FK2
  :ezid_placeholder_identifier: 10.5072/FK2

test:
  :admin_list: admin
  :local_mode: true
  :ezid_host: ezid.lib.purdue.edu
  :ezid_username: apitest
  :ezid_password: apitest
  :ezid_shoulder: doi:10.5072/FK2
  :ezid_placeholder_identifier: 10.5072/FK2

production:
  :admin_list: <%= ENV["ADMIN_LIST"] %>
  :local_mode: false
  :ezid_host: ezid.lib.purdue.edu
  :ezid_username: <%= ENV["EZID_USERNAME"] %>
  :ezid_password: <%= ENV["EZID_PASSWORD"] %>
  :ezid_shoulder: <%= ENV["EZID_SHOULDER"] %>
  :ezid_placeholder_identifier: 10.5072/FK2