development:
  host: rds-dev.library.illinois.edu
  uid_field: eppn
  extra_fields:
    - eppn
    - unscoped-affiliation
    - uid
    - sn
    - eduPersonNickName
  request_type: header
  info_fields:
    name: displayName
    email: mail


production:
  host: databank.illinois.edu
  uid_field: eppn
  extra_fields:
    - eppn
    - unscoped-affiliation
    - uid
    - sn
    - eduPersonNickName
  request_type: header
  info_fields:
    name: displayName
    email: mail
   
