development:
  host: https://rds-dev.library.illinois.edu/Shibboleth
  uid_field: eppn
  extra_fields:
    - eppn
    - unscoped-affiliation
    - uid
  request_type: header
  info_fields:
    name: displayName
    email: mail


production:
  host: databank.illinois.edu
  uid_field: eppn
  extra_fields:
    - eppn
    - unscoped-affiliation
    - uid
  request_type: header
  info_fields:
    name: displayName
    email: mail